import {sortMaterials,materialStatus} from './material-sort.mjs';
import {compareItems} from './sync.mjs';
import {allItemData} from './all-items.mjs';
import {resolveParent,rollupOrders} from './rollup.mjs';
import {catalog} from './catalog.mjs';
import {addDays,remaining,bucket,plan,demoData,receiptBucket,matchesProductLines,eligiblePO} from './core.mjs';
const $=s=>document.querySelector(s),nf=new Intl.NumberFormat('en-US',{maximumFractionDigits:6}),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n),fmt=s=>s?new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}):'Not scheduled',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const p=t=>parts.find(x=>x.type===t).value;const base=p('year')+'-'+p('month')+'-'+p('day');
// Swap this provider for a secure server endpoint when NetSuite is connected.
const dataProvider={async load(){return allItemData(catalog,base)}};
const data=await dataProvider.load();const productLines=[...new Set(data.materials.map(m=>m.productLine))].sort();let selectedProductLines=new Set(productLines);let rows=[],onlyReorder=false,materialPage=0,materialSortKey='sku',materialSortDirection='asc';const materialPageSize=60;const num=n=>Number.isFinite(n)?nf.format(n):'—';$('#report-date').value=base;
function options(){return {date:$('#report-date').value||base,days:Number($('#horizon').value),overdue:$('#overdue').checked,productLines:[...selectedProductLines]}}
function badge(type){return {near:'<span class="badge">In window</span>',future:'<span class="badge neutral">Future demand</span>',undated:'<span class="badge warn">Missing date · included today</span>',overdue:'<span class="badge warn">Overdue excluded</span>'}[type]||''}
function status(r){if(r.packingError)return '<span class="badge warn">Allocation needs review</span>';if(r.available!==null&&!Number.isFinite(r.reorder))return '<span class="badge warn">Missing reorder point</span>';return r.available===null?'<span class="badge neutral">Awaiting NetSuite</span>':r.shortage?'<span class="badge danger">Timing shortage</span>':r.suggested?'<span class="badge warn">Needs reorder</span>':'<span class="badge">Covered</span>'}
function render(){const o=options();rows=plan(data,o);$('#window-label').textContent=fmt(o.date)+' → '+fmt(addDays(o.date,o.days))+' · rolling '+o.days+' days';$('#days-label').textContent=o.days;const lines=rows.flatMap(r=>r.lines).filter(l=>bucket(l,o.date,o.days,o.overdue)!=='closed'),near=lines.filter(l=>['near','undated'].includes(bucket(l,o.date,o.days,o.overdue))),future=lines.filter(l=>bucket(l,o.date,o.days,o.overdue)==='future'),undated=lines.filter(l=>!l.ship);$('#date-alert').textContent=undated.length?undated.length+' order line missing a ship date':'';const reorder=rows.filter(r=>r.suggested>0),short=rows.filter(r=>r.shortage>0),count=ls=>new Set(ls.map(l=>l.order)).size;
$('#stats').innerHTML=[['Materials to reorder',nf.format(reorder.length),'Among '+rows.filter(r=>r.suggested!==null).length+' sample items with settings','↗'],['Orders in window',nf.format(count(near)),near.length+' material lines included','▦'],['Future orders excluded',nf.format(count(future)),'Visible, without reducing availability','⇥'],['Suggested order spend',money(rows.reduce((s,r)=>s+(r.cost||0),0)),'Sample purchase prices · USD','＄']].map(([a,b,c,d])=>`<div class="stat"><div class="stat-head">${a}<span class="stat-icon">${d}</span></div><div class="stat-value">${b}</div><div class="stat-note">${c}</div></div>`).join('');const excluded=lines.filter(l=>['undated','overdue'].includes(bucket(l,o.date,o.days,o.overdue))).length;$('#outlook-bar').innerHTML=lines.length?[['green',near.length],['gray',future.length],['amber',excluded]].filter(x=>x[1]).map(([c,n])=>`<span class="${c}" style="flex:${n}"></span>`).join(''):'<span class="gray" style="flex:1"></span>';$('#near-count').textContent=near.length;$('#future-count').textContent=future.length;$('#review-count').textContent=excluded;
const matching=visibleRows();const pages=Math.max(1,Math.ceil(matching.length/materialPageSize));materialPage=Math.min(materialPage,pages-1);const shown=matching.slice(materialPage*materialPageSize,(materialPage+1)*materialPageSize);$('#material-prev').disabled=materialPage===0;$('#material-next').disabled=materialPage===pages-1;$('#material-count').textContent=rows.length;$('#showing').textContent=nf.format(matching.length)+' matching purchasing items · Page '+(materialPage+1)+' of '+pages+' · '+rows.filter(r=>!r.sample).length+' awaiting NetSuite';$('#materials').innerHTML=shown.length?shown.map(r=>`<tr><td><button class="item-button" data-material="${r.id}">${esc(r.sku)} ↗</button><small>${esc(r.productLine)} · ${r.sample?'Sample data': 'Stock not connected'}</small></td><td>${num(r.onHand)}</td><td class="demand-cell">${num(r.demand)}</td><td class="subtle">${num(r.later)}</td><td class="${r.available<0?'negative':''}">${num(r.available)}</td><td>${num(r.supply)}</td><td class="subtle">${num(r.reorder)}</td><td class="subtle">${num(r.preferred)}</td><td><b>${num(r.suggested)}</b>${r.cost?`<small>${money(r.cost)}</small>`:''}</td><td>${status(r)}${r.undated?'<small>Missing date · included today</small>':''}${r.arrivalReview?'<small>Arrival date needs review</small>':''}${r.invalidYieldCount?'<small>Invalid yield · child skipped</small>':''}</td></tr>`).join(''):'<tr><td colspan="10" class="empty">No materials match these filters.</td></tr>';renderOrders();if(incomingReady)renderIncoming();if(typeof renderScenario==='function'&&scenarioReady)renderScenario()}
function visibleRows(){return sortMaterials(rows.filter(r=>(!onlyReorder||r.suggested>0)&&(r.sku+' '+r.name+' '+r.productLine).toLowerCase().includes($('#search').value.toLowerCase())),materialSortKey,materialSortDirection)}
function renderOrders(){const o=options(),filter=$('#order-filter').value;const lines=rows.flatMap(r=>r.lines).filter(l=>{const b=bucket(l,o.date,o.days,o.overdue);return b!=='closed'&&(filter==='all'||b===filter)}).sort((a,b)=>(a.ship||'9999').localeCompare(b.ship||'9999'));$('#orders').innerHTML=lines.length?lines.map(l=>{const m=rows.find(r=>r.id===l.material);return `<tr><td><b>${esc(l.order)}</b><small>${esc(l.customer)}</small></td><td>${esc(m.sku)}<small>${esc(l.product)}</small></td><td>${fmt(l.ship)}${l.ship&&l.ship<o.date?'<small class="negative">Overdue</small>':''}</td><td>${nf.format(remaining(l))} ${esc(m.unit)}</td><td>${badge(bucket(l,o.date,o.days,o.overdue))}</td></tr>`}).join(''):'<tr><td colspan="5" class="empty">No order lines in this category.</td></tr>'}
function showView(view){const text={inventory:['Inventory planner','Plan for what’s shipping next.','A clearer view of your material needs, without reserving stock for distant orders.'],incoming:['On order','See what’s on the way.','Track open purchases, remaining quantities, and expected arrival dates across all product lines.'],orders:['Order schedule','Every order. The right window.','See which orders count toward current demand and which are planned for later.'],catalog:['Item catalog','Plan around purchasing parents.','Your complete item list, with child relationships and parent yields.'],connection:['NetSuite connection','Your data, connected.','Start with a preview. Connect your live operations when you’re ready.']}[view];$('#product-line-controls').hidden=!['inventory','incoming','orders'].includes(view);$('#crumb').textContent=text[0];$('#page-title').textContent=text[1];$('#page-subtitle').textContent=text[2];$('#planner-view').hidden=view!=='inventory';$('#orders-view').hidden=view!=='orders';$('#incoming-view').hidden=view!=='incoming';$('#connection-view').hidden=view!=='connection';$('#catalog-view').hidden=view!=='catalog';$('#export').hidden=view==='connection'||view==='catalog'||view==='incoming';document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
function detail(id){const r=rows.find(r=>r.id===id),o=options();$('#detail-title').textContent=r.sku;$('#detail-subtitle').textContent=r.name+' · '+r.unit;if(!r.sample){$('#detail-body').innerHTML='<p>Item ID '+r.internalId+' · '+esc(r.productLine)+'</p><p>Inventory, open orders, purchase orders, and reorder settings for this purchasing item await NetSuite. Missing values are not treated as zero.</p><h3>Child items linked to this parent</h3><div class="linked-children">'+catalog.filter(i=>i.parent===r.sku&&i.sku!==r.sku).map(i=>'<p><b>'+esc(i.sku)+'</b> · yield '+(i.yield??'missing')+'</p>').join('')+'</div>';$('#detail').showModal();return}const open=r.lines.filter(l=>bucket(l,o.date,o.days,o.overdue)!=='closed');const table=ls=>ls.length?`<div class="table-scroll"><table><thead><tr><th>Order / customer</th><th>Ship date</th><th>Material required</th><th>Treatment</th></tr></thead><tbody>${ls.map(l=>`<tr><td><b>${esc(l.order)}</b><small>${esc(l.customer)}</small><small>${esc(l.calculation||'Parent units required for this order')}</small></td><td>${fmt(l.ship)}</td><td>${nf.format(remaining(l))} ${r.unit}</td><td>${badge(bucket(l,o.date,o.days,o.overdue))}</td></tr>`).join('')}</tbody></table></div>`:'<p>No order lines.</p>';
$('#detail-body').innerHTML=`<div class="detail-summary"><div><small>Usable on hand</small><b>${num(r.onHand)}</b></div><div><small>Near-term demand</small><b>${num(r.demand)}</b></div><div><small>Planning available</small><b class="${r.available<0?'negative':''}">${num(r.available)}</b></div></div><p>${num(r.onHand)} on hand − ${num(r.demand)} demand = ${num(r.available)} planning available (${r.unit}).</p>${r.shortage?`<div class="demo-banner"><b>Timing shortage: ${nf.format(r.shortage)} ${r.unit}</b> Stock may run out before scheduled receipts arrive.</div>`:''}<div class="detail-section"><h3>Included in this window</h3>${table(open.filter(l=>['near','undated'].includes(bucket(l,o.date,o.days,o.overdue))))}</div><div class="detail-section"><h3>Future demand · excluded from availability</h3>${table(open.filter(l=>bucket(l,o.date,o.days,o.overdue)==='future'))}</div>${open.some(l=>['overdue'].includes(bucket(l,o.date,o.days,o.overdue)))?`<div class="detail-section"><h3>Needs review · excluded from demand</h3>${table(open.filter(l=>['overdue'].includes(bucket(l,o.date,o.days,o.overdue))))}</div>`:''}<div class="detail-section"><h3>Incoming purchase orders</h3>${r.receipts.length?`<div class="table-scroll"><table><thead><tr><th>Purchase order</th><th>Expected arrival</th><th>Quantity</th><th>Counts toward reorder</th></tr></thead><tbody>${r.receipts.map(p=>`<tr><td>${p.order}</td><td>${fmt(p.date)}</td><td>${nf.format(p.qty)} ${r.unit}</td><td>Yes${!p.date||p.date<o.date?'<small>Arrival date needs review</small>':''}</td></tr>`).join('')}</tbody></table></div>`:'<p>No incoming purchase orders for this material.</p>'}</div><div class="detail-section"><h3>${!Number.isFinite(r.reorder)?'Missing reorder point · ':''}Suggested purchase: ${num(r.suggested)} ${r.unit} · ${money(r.cost)}</h3><p>Projected balance: ${num(r.available)} available + ${num(r.supply)} incoming = ${nf.format(r.projected)}. ${!Number.isFinite(r.reorder)?'No purchase suggestion until a reorder point is supplied.':r.suggested?`Below reorder point ${num(r.reorder)}; suggested quantity restores the reorder point of ${num(r.reorder)}.`:`At or above reorder point ${num(r.reorder)}; no purchase suggested.`}</p><p>All open PO balances count toward reorder coverage. Material is needed on the ship date. Same-day arrivals count as available for demand. Missing or overdue arrival dates need review.</p></div>`;$('#detail').showModal()}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#toast').textContent='Downloaded '+name;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2800)}
$('#export').onclick=()=>{const o=options(),header=['Report date','Cutoff date','Material','Unit','On hand','Near-term demand','Future demand','Planning available','All open PO quantity','Projected balance','Reorder point','Preferred stock','Suggested order','Last purchase price USD','Est cost USD','Timing shortage','Missing date lines'];const vals=visibleRows().map(r=>[o.date,addDays(o.date,o.days),r.sku,r.unit,r.onHand,r.demand,r.later,r.available,r.supply,r.projected,r.reorder,r.preferred,r.suggested,r.price,r.cost,r.shortage,r.undated]);download('inventory-planning-'+o.date+'.csv',[header,...vals].map(row=>row.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv')};
$('#download-sample').onclick=()=>download('snap-sample-data.json',JSON.stringify(data,null,2),'application/json');document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));['setup','connection-top'].forEach(id=>$('#'+id).onclick=()=>showView('connection'));$('#back-planner').onclick=()=>showView('inventory');$('#future-link').onclick=()=>{$('#order-filter').value='future';renderOrders();showView('orders')};$('#about').onclick=()=>$('#help').showModal();$('#close-help').onclick=()=>$('#help').close();$('#close-detail').onclick=()=>$('#detail').close();$('#materials').onclick=e=>{const b=e.target.closest('[data-material]');if(b)detail(b.dataset.material)};['report-date','horizon','overdue'].forEach(id=>$('#'+id).addEventListener('change',()=>{if(id==='report-date'&&!$('#report-date').value)$('#report-date').value=base;render()}));$('#search').addEventListener('input',()=>{materialPage=0;render()});$('#order-filter').addEventListener('change',renderOrders);$('#reorder-only').onclick=()=>{onlyReorder=!onlyReorder;$('#reorder-only').classList.toggle('selected',onlyReorder);$('#reorder-only').setAttribute('aria-pressed',onlyReorder);render()};let scenarioReady=false,incomingReady=false;

const nameCounts=new Map();catalog.forEach(i=>nameCounts.set(i.sku,(nameCounts.get(i.sku)||0)+1));
const byName=new Map(catalog.map(i=>[i.sku,i]));
const role=i=>!i.parent||i.parent===i.sku?'purchase':'child';
function review(i){const issues=[];if(nameCounts.get(i.sku)>1)issues.push('Separate item record by ID');if(role(i)==='child'){if(!nameCounts.has(i.parent))issues.push('Ignored: parent not found');if(nameCounts.get(i.parent)>1)issues.push('Parent name ambiguous');if(i.yield==null)issues.push('Missing yield: uses 1');else if(!(i.yield>0))issues.push('Invalid yield');const p=byName.get(i.parent);if(p&&role(p)==='child')issues.push('Usage shown at both levels')}return issues}
let catalogPage=0;const pageSize=60;
function renderCatalog(){const q=$('#catalog-search').value.toLowerCase(),filter=$('#catalog-filter').value;const selected=catalog.filter(i=>(i.sku+' '+(i.parent||'')+' '+(i.description||'')+' '+i.id).toLowerCase().includes(q)&&(filter==='all'||filter===role(i)||filter==='review'&&review(i).length));const pages=Math.max(1,Math.ceil(selected.length/pageSize));catalogPage=Math.min(catalogPage,pages-1);const visible=selected.slice(catalogPage*pageSize,(catalogPage+1)*pageSize);$('#catalog-summary').textContent=nf.format(catalog.length)+' items · '+nf.format(catalog.filter(i=>role(i)==='purchase').length)+' purchasing items · '+nf.format(catalog.filter(i=>role(i)==='child').length)+' child items';$('#catalog-rows').innerHTML=visible.length?visible.map(i=>`<tr><td><b>${esc(i.sku)}</b><small>ID ${i.id} · ${esc(i.type)}</small><small>${esc(i.description||i.display||'')}</small></td><td>${esc(i.parent||i.sku)}${!i.parent?'<small>No parent assigned</small>':''}</td><td>${i.yield===null?'1 (assumed)':String(i.yield)}</td><td><span class="badge ${role(i)==='child'?'neutral':''}">${role(i)==='child'?'Child item':'Purchasing item'}</span></td><td>${review(i).length?review(i).map(x=>'<span class="badge warn">'+x+'</span>').join('<br>'):'<span class="subtle">—</span>'}<br><button class="catalog-test" data-test-item="${i.id}">Test item</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No items match these filters.</td></tr>';$('#catalog-showing').textContent=nf.format(selected.length)+' matching items · Page '+(catalogPage+1)+' of '+pages;$('#catalog-prev').disabled=catalogPage===0;$('#catalog-next').disabled=catalogPage===pages-1}
$('#catalog-search').addEventListener('input',()=>{catalogPage=0;renderCatalog()});$('#catalog-filter').addEventListener('change',()=>{catalogPage=0;renderCatalog()});$('#catalog-prev').onclick=()=>{catalogPage--;renderCatalog()};$('#catalog-next').onclick=()=>{catalogPage++;renderCatalog()};renderCatalog();

let scenarioSeq=0;let scenario=[{id:++scenarioSeq,itemId:863,qty:80,ship:addDays(base,30)},{id:++scenarioSeq,itemId:31,qty:40,ship:addDays(base,45)},{id:++scenarioSeq,itemId:863,qty:800,ship:addDays(base,240)}];scenarioReady=true;
function scenarioExplanation(line){
 if(line.ignored)return 'Ignored · '+line.reason+' · no demand counted';
 if(line.error)return line.error;
 return 'Order '+(line.order||'TEST-'+line.id)+' · shared order totals: '+line.usage.map(level=>nf.format(level.qty)+' of '+level.parent.sku+' (ID '+level.parent.id+')').join(' → ')+(line.path.some(p=>p.assumedYield)?' · missing yield assumed 1':'')+' · '+(['near','undated'].includes(line.treatment)?'included':line.treatment==='future'?'future demand':'excluded / review');
}
function renderScenario(keepInputs=false){
 const o=options(),result=rollupOrders(scenario,catalog,o.date,o.days,o.overdue,bucket);
 if(!keepInputs)$('#scenario-lines').innerHTML=result.details.length?result.details.map(l=>`<div class="scenario-row"><div><b>${esc(l.item?.sku||'Unknown item')} <span class="subtle">· ID ${esc(l.itemId)}</span></b><small>${esc(scenarioExplanation(l))}</small></div><label>Order number<input type="text" value="${esc(l.order||'TEST-'+l.id)}" data-scenario="${l.id}" data-field="order"></label><label>Child / item quantity<input type="number" min="0" step="any" value="${l.qty}" data-scenario="${l.id}" data-field="qty"></label><label>Ship date<input type="date" value="${l.ship||''}" data-scenario="${l.id}" data-field="ship"></label><button class="close" data-remove="${l.id}" aria-label="Remove test line for ${esc(l.item?.sku||'unknown item')}">×</button></div>`).join(''):'<p>No test lines. Search the catalog and choose Test item.</p>';
 if(keepInputs)for(const line of result.details){$('#scenario-lines [data-scenario="'+line.id+'"]').closest('.scenario-row').querySelector('small').textContent=scenarioExplanation(line)}
 $('#scenario-notes').textContent=result.details.filter(l=>l.ignored).length+' test lines ignored because a parent was not found. Parent levels are listed separately; their quantities are not added together as one material.';
 $('#scenario-totals').innerHTML=result.groups.length?result.groups.map(g=>`<tr><td><b>${esc(g.parent.sku)}</b><small>ID ${g.parent.id} · ${g.purchasing?'Purchasing parent':'Intermediate parent usage'}</small></td><td>${nf.format(g.demand)}</td><td>${nf.format(g.future)}</td><td class="subtle">${g.purchasing?'Awaiting NetSuite':'Usage only'}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No parent usage to count.</td></tr>';
}
$('#catalog-rows').addEventListener('click',e=>{const b=e.target.closest('[data-test-item]');if(b){scenario.push({id:++scenarioSeq,itemId:Number(b.dataset.testItem),qty:10,ship:addDays(options().date,30)});renderScenario();$('.rollup-card').scrollIntoView({behavior:'smooth',block:'start'})}});$('#scenario-lines').addEventListener('input',e=>{const id=Number(e.target.dataset.scenario),field=e.target.dataset.field,l=scenario.find(x=>x.id===id);if(l&&field){l[field]=field==='qty'?Math.max(0,Number(e.target.value)):e.target.value||null;renderScenario(true)}});$('#scenario-lines').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){scenario=scenario.filter(x=>x.id!==Number(b.dataset.remove));renderScenario()}});$('#reset-scenario').onclick=()=>{scenario=[];renderScenario()};renderScenario();


$('#material-prev').onclick=()=>{materialPage--;render()};$('#material-next').onclick=()=>{materialPage++;render()};
function incomingLines(){const o=options(),q=$('#incoming-search').value.toLowerCase(),filter=$('#incoming-filter').value;return data.receipts.filter(eligiblePO).map(r=>({...r,item:data.materials.find(m=>m.id===r.material),timing:receiptBucket(r,o.date,o.days)})).filter(r=>r.item&&matchesProductLines(r.item.productLine,o)&&(filter==='all'||r.timing===filter)&&(r.item.sku+' '+r.order+' '+r.vendor+' '+r.item.productLine).toLowerCase().includes(q)).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'))}
const receiptLabel={window:'Due in window',overdue:'Overdue',future:'Future receipt',undated:'Missing date'};
function renderIncoming(){const ls=incomingLines();$('#incoming-stats').innerHTML=[['Open purchase orders',new Set(ls.map(l=>l.order)).size],['Due in planning window',ls.filter(l=>l.timing==='window').length],['Overdue receipts',ls.filter(l=>l.timing==='overdue').length],['Missing receipt dates',ls.filter(l=>l.timing==='undated').length]].map(([a,b])=>'<div class="stat"><div class="stat-head">'+a+'</div><div class="stat-value">'+b+'</div><div class="stat-note">Sample purchase orders · current filters</div></div>').join('');$('#incoming-rows').innerHTML=ls.length?ls.map(l=>`<tr><td><button class="item-button" data-material="${l.item.id}">${esc(l.item.sku)} ↗</button><small>${esc(l.item.productLine)} · ${esc(l.item.unit)}</small></td><td>${esc(l.order)}<small>${esc(l.vendor)}</small></td><td>${num(l.ordered)}</td><td>${num(l.received)}</td><td><b>${num(l.qty)}</b></td><td>${fmt(l.date)}</td><td><span class="badge ${l.timing==='overdue'||l.timing==='undated'?'warn':l.timing==='future'?'neutral':''}">${receiptLabel[l.timing]}</span>${['undated','overdue'].includes(l.timing)?'<small>Arrival date needs review</small>':''}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">No sample purchase orders match these filters. Live purchasing data awaits NetSuite.</td></tr>';$('#incoming-showing').textContent=ls.length+' open purchase-order lines · '+fmt(options().date)+' → '+fmt(addDays(options().date,options().days))}
$('#incoming-search').addEventListener('input',renderIncoming);$('#incoming-filter').addEventListener('change',renderIncoming);$('#incoming-rows').onclick=e=>{const b=e.target.closest('[data-material]');if(b)detail(b.dataset.material)};$('#export-incoming').onclick=()=>{const ls=incomingLines(),header=['Item','Product line','PO','Supplier','Ordered','Received','Remaining','Unit','Expected arrival','Timing','Data source'];const vals=ls.map(l=>[l.item.sku,l.item.productLine,l.order,l.vendor,l.ordered,l.received,l.qty,l.item.unit,l.date||'',receiptLabel[l.timing],'Sample']);download('items-on-order-'+options().date+'.csv',[header,...vals].map(row=>row.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv')};incomingReady=true;renderProductPicker();render();

function renderProductPicker(){const listScroll=$('#product-line-options').scrollTop,focusedLine=document.activeElement?.dataset?.productLine;const q=$('#product-line-search').value.trim().toLowerCase(),shown=productLines.filter(line=>line.toLowerCase().includes(q)),n=selectedProductLines.size;$('#product-picker-summary').textContent=n===productLines.length?'All product lines ('+n+')':n===0?'No product lines selected':n+' product lines selected';$('#product-line-options').innerHTML=shown.length?shown.map(line=>`<label class="product-option"><input type="checkbox" data-product-line="${esc(line)}" ${selectedProductLines.has(line)?'checked':''}><span>${esc(line)}</span><small>${nf.format(data.materials.filter(m=>m.productLine===line).length)}</small></label>`).join(''):'<p>No product lines match your search.</p>';$('#product-line-options').scrollTop=listScroll;if(focusedLine)[...$('#product-line-options').querySelectorAll('input')].find(el=>el.dataset.productLine===focusedLine)?.focus({preventScroll:true});$('#product-picker-count').textContent=n+' of '+productLines.length+' selected · changes apply immediately';$('#selected-product-lines').innerHTML=n===productLines.length?'<span class="product-selection-note">All product lines are on.</span>':n===0?'<span class="product-selection-note">All product lines are off. Turn on a line to view its items.</span>':[...selectedProductLines].sort().map(line=>`<button class="product-chip" data-remove-line="${esc(line)}" aria-label="Turn off ${esc(line)}">${esc(line)} <span aria-hidden="true">×</span></button>`).join('')}
function updateProductSelection(){materialPage=0;renderProductPicker();render()}
$('#product-line-options').addEventListener('change',e=>{const line=e.target.dataset.productLine;if(line){if(e.target.checked)selectedProductLines.add(line);else selectedProductLines.delete(line);updateProductSelection()}});$('#selected-product-lines').addEventListener('click',e=>{const b=e.target.closest('[data-remove-line]');if(b){selectedProductLines.delete(b.dataset.removeLine);updateProductSelection()}});$('#product-line-search').addEventListener('input',renderProductPicker);$('#select-all-lines').onclick=()=>{selectedProductLines=new Set(productLines);updateProductSelection()};$('#clear-all-lines').onclick=()=>{selectedProductLines.clear();updateProductSelection()};$('#product-picker').addEventListener('keydown',e=>{if(e.key==='Escape'){$('#product-picker').open=false;$('#product-picker-summary').focus()}});document.addEventListener('click',e=>{if(!e.composedPath().includes($('#product-picker')))$('#product-picker').open=false});

// Demonstrate reconciliation in isolation. No live data or catalog mutation occurs.
let syncPreviewReport=null;
function openRefresh(mode){
  syncPreviewReport=null;$('#sync-title').textContent=mode==='items'?'Update items':'Refresh report';
  $('#preview-sync').hidden=mode!=='items';$('#export-sync').hidden=true;
  $('#sync-body').innerHTML=mode==='items'?`<div class="demo-banner"><b>NetSuite is not connected</b></div><p>Once connected, this button will pull all items across every product line, match them by NetSuite internal ID, and update names, parent relationships, yields, and other item information. New items will be added; items no longer returned will be removed from the active tool catalog.</p><p>You’ll receive counts and a detailed before-and-after report. Removals require a complete, unfiltered pull with the same account and access scope. If the pull fails, the last successful catalog stays in place.</p><p>Preview the report below using hypothetical changes to three catalog items. Your imported catalog stays as it is.</p>`:`<div class="demo-banner"><b>NetSuite is not connected</b></div><p>Once connected, this button will retrieve current parent inventory and reorder points, Pending Fulfillment sales orders with ship date and whole-order inspection status, and remaining open purchase-order quantities. It will then recalculate the planning report for the selected window.</p><p>The connected workflow will require no recurring file uploads. A successful refresh will show its completion time and any records needing review. If a pull fails, the tool will retain the last complete report and clearly show when it was last refreshed.</p><p>This preview currently uses the imported item catalog and sample operating data.</p>`;
  $('#sync-dialog').showModal();
}
$('#update-items').onclick=()=>openRefresh('items');$('#refresh-data').onclick=()=>openRefresh('report');$('#close-sync').onclick=()=>$('#sync-dialog').close();
$('#preview-sync').onclick=()=>{
  const demonstration=catalog.slice(0,3).map(i=>({...i}));
  const next=[{...demonstration[0],yield:0.35},demonstration[1],{...demonstration[2],id:'PREVIEW-NEW-ITEM',sku:'EXAMPLE-NEW-PARENT',parent:'EXAMPLE-NEW-PARENT'}];
  syncPreviewReport=compareItems(demonstration,{items:next,complete:true,filtered:false,scope:'preview'},'preview');
  const labels={yield:'Parent yield',line:'Product line'};
  $('#sync-body').innerHTML=`<div class="demo-banner"><b>Example change report · No changes applied</b></div><p>Hypothetical comparison of three items, generated ${esc(new Date().toLocaleString())}. This is not a NetSuite refresh.</p><div class="sync-summary">${Object.entries(syncPreviewReport.counts).map(([key,n])=>`<div><b>${n}</b><small>${key==='removed'?'Removed from tool':key[0].toUpperCase()+key.slice(1)}</small></div>`).join('')}</div><div class="table-scroll"><table><thead><tr><th>Action</th><th>Item / internal ID</th><th>Changed field</th><th>Before</th><th>After</th></tr></thead><tbody>${syncPreviewReport.changes.map(c=>`<tr><td>${esc(c.action)}</td><td>${esc(c.sku)}<small>${esc(c.id)}</small></td><td>${esc(labels[c.field]||c.field)}</td><td>${esc(c.before??'—')}</td><td>${esc(c.after??'—')}</td></tr>`).join('')}</tbody></table></div><p>“Removed from tool” means removed from the active planning catalog. Historical refresh reports will retain the item’s identity. These actions do not change item records in NetSuite.</p>`;
  $('#preview-sync').hidden=true;$('#export-sync').hidden=false;
};
$('#export-sync').onclick=()=>{if(!syncPreviewReport)return;const content=[['Data source','Action','Internal ID','Item','Field','Before','After'],...syncPreviewReport.changes.map(c=>['Hypothetical preview',c.action,c.id,c.sku,c.field,c.before,c.after])].map(row=>row.map(value=>'"'+String(value??'').replaceAll('"','""')+'"').join(',')).join('\r\n');download('example-item-changes-'+base+'.csv',content,'text/csv')};

// Sort the complete filtered result before pagination; exports use the same order.
document.querySelectorAll('.material-sort').forEach(button=>button.addEventListener('click',()=>{
 const key=button.dataset.sort;materialSortDirection=key===materialSortKey&&materialSortDirection==='asc'?'desc':'asc';materialSortKey=key;materialPage=0;
 document.querySelectorAll('.material-sort').forEach(header=>{
  const active=header.dataset.sort===materialSortKey;
  header.closest('th').setAttribute('aria-sort',active?(materialSortDirection==='asc'?'ascending':'descending'):'none');
  header.querySelector('.sort-arrow').textContent=active?(materialSortDirection==='asc'?'↑':'↓'):'↕';
 });render();
}));
