import {packParent} from './packing.mjs';
export const addDays=(s,n)=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+Number(n));return d.toISOString().slice(0,10)};
export const inspectedOrder=l=>[true,'T','true','1',1].includes(l.inspected??l.custbodyqa_check);
export const eligibleOrder=l=>!l.closed&&!l.cancelled&&(l.source==='workOrder'?['Planned','Released','In Process'].includes(l.status):!inspectedOrder(l)&&l.status==='Pending Fulfillment');
export const remaining=l=>{const qty=Math.max(0,l.ordered-l.shipped),yieldValue=l.factor??1;return yieldValue>0&&yieldValue<1?Math.ceil(qty/Math.floor(1/yieldValue)):qty*yieldValue};
export const bucket=(l,date,days,overdue)=>{if(!eligibleOrder(l)||remaining(l)===0)return 'closed';if(!l.ship)return 'undated';if(l.ship<date)return overdue?'near':'overdue';return l.ship<=addDays(date,days)?'near':'future'};
export const matchesProductLines=(line,opt)=>Array.isArray(opt.productLines)?opt.productLines.includes(line):(!opt.productLine||opt.productLine==='All product lines'||line===opt.productLine);
export const eligiblePO=r=>r.approved===true&&!r.closed&&!r.cancelled&&r.qty>0;
export const eligibleWO=r=>!r.closed&&!r.cancelled&&r.qty>0&&['Planned','Released','In Process'].includes(r.status);
export function consolidateOrderItems(lines){
 if(lines.every(l=>l.preRolledUp===true))return lines.map(l=>({...l,invalidYields:l.invalidYields||[]}));
 const grouped=new Map();for(const line of lines){const key=JSON.stringify([line.order||line.id,line.material,line.ship,line.status,inspectedOrder(line),!!line.closed,!!line.cancelled]);
 if(!grouped.has(key))grouped.set(key,{...line,parts:[]});
 const group=grouped.get(key);group.parts.push({itemId:line.itemId,product:line.product,qty:Math.max(0,line.ordered-line.shipped),yield:line.factor??1});}
 return [...grouped.values()].map(group=>{
  const invalidYields=group.parts.filter(p=>{const y=p.yield==null||String(p.yield).trim()===''?1:Number(p.yield);return !Number.isFinite(y)||y<=0;});
  const validParts=group.parts.filter(p=>!invalidYields.includes(p));const packed=packParent(validParts);
  return {...group,product:group.parts.map(p=>p.product).filter(Boolean).join(' + '),ordered:packed.qty??0,shipped:0,factor:1,invalidYields,packingError:group.packingError||packed.error,calculation:validParts.map(p=>p.qty+' × yield '+p.yield+' '+(p.product||'item')).join('; ')+' · shared within this order'};
 });
}
export function plan(data,opt){return data.materials.filter(m=>matchesProductLines(m.productLine,opt)).map(m=>{
 const lines=consolidateOrderItems(data.lines.filter(l=>l.material===m.id)),near=lines.filter(l=>bucket(l,opt.date,opt.days,opt.overdue)==='near'),future=lines.filter(l=>bucket(l,opt.date,opt.days,opt.overdue)==='future');
 const receipts=data.receipts.filter(r=>r.material===m.id&&eligiblePO(r)),incoming=receipts;
 const packingError=lines.find(l=>eligibleOrder(l)&&l.packingError&&(!l.ship||(l.ship<=addDays(opt.date,opt.days)&&(opt.overdue||l.ship>=opt.date))))?.packingError;const known=m.hasDemandData!==false&&!packingError,demand=known?lines.filter(l=>['near','undated'].includes(bucket(l,opt.date,opt.days,opt.overdue))).reduce((s,l)=>s+remaining(l),0):null,later=known?future.reduce((s,l)=>s+remaining(l),0):null,supply=m.hasSupplyData===false?null:incoming.reduce((s,r)=>s+r.qty,0);
 const workOrderReceipts=(data.workOrderReceipts||[]).filter(r=>r.material===m.id&&eligibleWO(r)),workOrderSupply=workOrderReceipts.reduce((sum,r)=>sum+r.qty,0);
 const workOrderDemand=known?lines.filter(l=>l.source==='workOrder'&&['near','undated'].includes(bucket(l,opt.date,opt.days,opt.overdue))).reduce((sum,l)=>sum+remaining(l),0):null;
 const available=Number.isFinite(m.onHand)&&demand!==null?m.onHand-demand:null,projected=available!==null&&supply!==null?available+supply+workOrderSupply:null;
 const suggested=projected!==null&&Number.isFinite(m.reorder)?Math.max(0,Math.ceil(m.reorder-projected)):null;
 let balance=m.onHand,low=balance;
 const events=[...lines.filter(l=>['near','undated'].includes(bucket(l,opt.date,opt.days,opt.overdue))).map(l=>({date:!l.ship||l.ship<opt.date?opt.date:l.ship,qty:-remaining(l)})),...[...incoming,...workOrderReceipts].filter(r=>r.date&&r.date>=opt.date&&r.date<=addDays(opt.date,opt.days)).map(r=>({date:r.date,qty:r.qty}))].sort((a,b)=>a.date.localeCompare(b.date)||b.qty-a.qty);
 for(const e of events){balance+=e.qty;low=Math.min(low,balance)}
 return {...m,packingError,invalidYieldCount:lines.reduce((n,l)=>n+(l.invalidYields?.length||0),0),arrivalReview:[...receipts,...workOrderReceipts].filter(r=>!r.date||r.date<opt.date).length,lines,near,future,receipts,incoming,workOrderReceipts,workOrderSupply,workOrderDemand,demand,later,supply,available,projected,suggested,cost:suggested!==null&&Number.isFinite(m.price)?suggested*m.price:null,shortage:available!==null?Math.max(0,-low):null,undated:lines.filter(l=>bucket(l,opt.date,opt.days,opt.overdue)==='undated').length};
})};
export const receiptBucket=(r,date,days)=>!r.date?'undated':r.date<date?'overdue':r.date<=addDays(date,days)?'window':'future';
export function demoData(base){const defs=[['SNAP-CONNECTOR-102-BK','Connector · 102 in',546,588,788,4.85],['SNAP-CORNER-POST-102','Corner post · 102 in',121,50,76,19.5],['SNAP-DOOR-90-BK','Door profile · 90 in',103,100,150,42],['SNAP-HINGE-BK','Hinge extrusion',131,50,100,8.25],['SNAP-HORZ-120-BK','Horizontal rail · 120 in',156,100,150,15.8],['SNAP-INSET-GASKET-32','Inset gasket · 32 in',474,250,500,1.95],['SNAP-INSET-GASKET-94','Inset gasket · 94 in',457,250,500,3.4],['SNAP-JAMB-90-BK','Door jamb · 90 in',41,60,125,21.4],['SNAP-MAGNET-TAPE','Magnetic tape',608,500,750,0.85],['SNAP-SPACER-FOAM','Foam spacer',12715,10000,15000,0.12],['SNAP-STUD-RAW','Raw stud stock',10,20,50,11.5],['SNAP-THRESHOLD-BK','Threshold extrusion',14,25,60,24],['SNAP-TURN-HANDLE-BK','Turn handle',26,15,20,17.75],['SNAP-VERT-102-BK','Vertical rail · 102 in',246,250,450,18.2],['Z-CLIP','Mounting clip',39,50,150,1.15]];const materials=defs.map((d,i)=>({id:'m'+i,sku:d[0],name:d[1],onHand:d[2],reorder:d[3],preferred:d[4],price:d[5],unit:i===9?'ft':'ea',location:i===10||i===11?'Fabrication':'Main warehouse'}));const lines=[];materials.forEach((m,i)=>{const qty=i===9?3200:[75,12,45,28,40,120,90,30,140,0,8,12,10,65,30][i];lines.push({id:'l'+i+'a',material:m.id,order:'SO-10428',customer:'Lakeside Commercial',product:m.sku,ordered:qty+10,shipped:10,factor:1,issued:0,ship:addDays(base,18),closed:false,status:'Pending Fulfillment',inspected:false});lines.push({id:'l'+i+'b',material:m.id,order:'SO-10451',customer:'Northline Interiors',product:i===0?'SNAP partition assembly':m.sku,ordered:i===9?1800:i===0?40:Math.ceil(qty*.55),shipped:0,factor:i===0?2:1,issued:0,ship:addDays(base,65),closed:false,status:'Pending Fulfillment',inspected:false});lines.push({id:'l'+i+'c',material:m.id,order:'SO-10502',customer:'Summit Development',product:m.sku,ordered:i===9?6000:Math.ceil(qty*2.4),shipped:0,factor:1,issued:0,ship:addDays(base,240),closed:false,status:'Pending Fulfillment',inspected:false});});lines.push({id:'late',material:'m7',order:'SO-10396',customer:'West End Builders',product:'SNAP-JAMB-90-BK',ordered:12,shipped:4,factor:1,issued:0,ship:addDays(base,-8),closed:false,status:'Pending Fulfillment',inspected:false},{id:'missing',material:'m2',order:'SO-10488',customer:'Harbor Office',product:'SNAP-DOOR-90-BK',ordered:20,shipped:0,factor:1,issued:0,ship:null,closed:false,status:'Pending Fulfillment',inspected:false},{id:'closed',material:'m0',order:'SO-10312',customer:'Cedar Construction',product:'SNAP-CONNECTOR-102-BK',ordered:100,shipped:0,factor:1,issued:0,ship:addDays(base,5),closed:true,status:'Pending Fulfillment',inspected:false});const receipts=[{material:'m7',order:'PO-2094',qty:120,approved:true,date:addDays(base,40)},{material:'m13',order:'PO-2101',qty:100,approved:true,date:addDays(base,45)},{material:'m2',order:'PO-2109',qty:60,approved:true,date:addDays(base,130)}];return {materials,lines,receipts}}
